//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDIMS.admin {
	
	
	public partial class update_vehicle {
		
		protected System.Web.UI.HtmlControls.HtmlForm searchform;
		
		protected System.Web.UI.WebControls.TextBox make;
		
		protected System.Web.UI.WebControls.TextBox model;
		
		protected System.Web.UI.WebControls.TextBox year;
		
		protected System.Web.UI.WebControls.TextBox extColor;
		
		protected System.Web.UI.WebControls.TextBox intColor;
		
		protected System.Web.UI.WebControls.DropDownList condition;
		
		protected System.Web.UI.WebControls.TextBox Mileage;
		
		protected System.Web.UI.WebControls.TextBox cMpg;
		
		protected System.Web.UI.WebControls.TextBox hMpg;
		
		protected System.Web.UI.WebControls.TextBox engine;
		
		protected System.Web.UI.WebControls.TextBox transmission;
		
		protected System.Web.UI.WebControls.DropDownList location;
		
		protected System.Web.UI.WebControls.TextBox price;
		
		protected System.Web.UI.WebControls.TextBox vin;
		
		protected System.Web.UI.WebControls.Button updateButton;
	}
}
