//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDIMS.vehicle {
	
	
	public partial class search {
		
		protected System.Web.UI.HtmlControls.HtmlForm searchform;
		
		protected System.Web.UI.WebControls.TextBox make;
		
		protected System.Web.UI.WebControls.TextBox model;
		
		protected System.Web.UI.WebControls.TextBox color;
		
		protected System.Web.UI.WebControls.TextBox year;
		
		protected System.Web.UI.WebControls.TextBox minprice;
		
		protected System.Web.UI.WebControls.TextBox maxprice;
		
		protected System.Web.UI.WebControls.DropDownList condition;
		
		protected System.Web.UI.WebControls.DropDownList location;
		
		protected System.Web.UI.WebControls.Button searchButton;
	}
}
